# Data Time Series (Tugas 3)

1.  Load data time series
2.  Membentuk data matrix

In [4]:
import pandas as pd

psg = pd.read_csv("/content/drive/MyDrive/prosaindata/tugas/airline-passengers.csv")

psg.head()


Month  Passengers
0  1949-01         112
1  1949-02         118
2  1949-03         132
3  1949-04         129
4  1949-05         121

In [ ]:
#memisahkan fitur dan label
feature=psg.iloc[:,0].values
label=psg.iloc[:,1].values

In [38]:
# from numpy import array
# # split a univariate sequence into samples
# def split_sequence(sequence, n_steps):
#   X, y = list(), list()
#   for i in range(len(sequence)):
#     end_ix = i + n_steps
#     if end_ix > len(sequence)-1:
#       break
#     # gather input and output parts of the pattern
#     seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
#     X.append(seq_x)
#     y.append(seq_y)
#   return array(X), array(y)

from numpy import array
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
  X = list()
  for i in range(len(sequence)):
    end_ix = i + n_steps
    if end_ix > len(sequence)-1:
      break
    # gather input and output parts of the pattern
    seq_x = sequence[i:end_ix]
    X.append(seq_x)
  return X

In [39]:
# transform to a supervised learning problem
X = split_sequence(label, 3)
# show each sample
for i in range(len(X)):
  print(X[i])

[112 118 132]
[118 132 129]
[132 129 121]
[129 121 135]
[121 135 148]
[135 148 148]
[148 148 136]
[148 136 119]
[136 119 104]
[119 104 118]
[104 118 115]
[118 115 126]
[115 126 141]
[126 141 135]
[141 135 125]
[135 125 149]
[125 149 170]
[149 170 170]
[170 170 158]
[170 158 133]
[158 133 114]
[133 114 140]
[114 140 145]
[140 145 150]
[145 150 178]
[150 178 163]
[178 163 172]
[163 172 178]
[172 178 199]
[178 199 199]
[199 199 184]
[199 184 162]
[184 162 146]
[162 146 166]
[146 166 171]
[166 171 180]
[171 180 193]
[180 193 181]
[193 181 183]
[181 183 218]
[183 218 230]
[218 230 242]
[230 242 209]
[242 209 191]
[209 191 172]
[191 172 194]
[172 194 196]
[194 196 196]
[196 196 236]
[196 236 235]
[236 235 229]
[235 229 243]
[229 243 264]
[243 264 272]
[264 272 237]
[272 237 211]
[237 211 180]
[211 180 201]
[180 201 204]
[201 204 188]
[204 188 235]
[188 235 227]
[235 227 234]
[227 234 264]
[234 264 302]
[264 302 293]
[302 293 259]
[293 259 229]
[259 229 203]
[229 203 229]
[203 229 242]
[229 2

In [53]:
df = pd.DataFrame(X, columns=['Input1', 'Input2', 'Output'])

path = '/content/drive/MyDrive/prosaindata/tugas/timeSeriesPassanger.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df.to_csv(f)

ts = pd.read_csv('/content/drive/MyDrive/prosaindata/tugas/timeSeriesPassanger.csv')
ts



Unnamed: 0  Input1  Input2  Output
0             0     112     118     132
1             1     118     132     129
2             2     132     129     121
3             3     129     121     135
4             4     121     135     148
..          ...     ...     ...     ...
136         136     472     535     622
137         137     535     622     606
138         138     622     606     508
139         139     606     508     461
140         140     508     461     390

[141 rows x 4 columns]